# Generated by Django 3.1.3 on 2020-11-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthday', models.CharField(max_length=10)),
                ('birth_city', models.CharField(max_length=255)),
                ('birth_state', models.CharField(max_length=255)),
            ],
        ),
    ]
