# Generated by Django 3.1.3 on 2020-11-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkSUM', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
