# Generated by Django 3.1.3 on 2020-11-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkSUM', '0003_token_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
